apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: otterdog
  labels:
    app: valkey
    environment: dev
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: valkey
    environment: dev
