version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/otterdog/webapp/static"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
