# adapted from https://docs.readthedocs.io/en/latest/build-customization.html#install-dependencies-with-poetry

version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install "poetry==1.8.4"
    post_install:
      # Install only dependencies of 'docs' dependency group
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry install --only=docs

mkdocs:
  configuration: mkdocs.yml
