valkey:
  enabled: true
  auth:
    enabled: true

mongodb:
  enabled: true
  auth:
    enabled: true

config:
  debug: true
  configRepo: "otterdog-configs"
  configPath: "otterdog.json"

github:
  webhookValidationContext: "otterdog/otterdog-validation"
  webhookSyncContext: "otterdog/otterdog-sync"
