services:
  webapp:
    restart: always
    depends_on:
      - mongodb
      - redis
      - ghproxy
    env_file: ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ../approot:/app/work
      - ../github-app:/app/work/config

  init-webapp:
    image: curlimages/curl:8.2.1
    command: sh /app/init-webapp webapp 5000
    volumes:
      - ./init-webapp:/app/init-webapp
    depends_on:
      webapp:
          condition: service_started

  mongodb:
    image: mongo:7.0.5
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    volumes:
      - ../approot/db:/data/db

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ../approot/cache:/data/

  ghproxy:
    image: us-docker.pkg.dev/k8s-infra-prow/images/ghproxy:v20240923-efb534162
    restart: always
    command:
      - --redis-address=redis:6379
      - --legacy-disable-disk-cache-partitions-by-auth-header=false
      - --throttling-time-ms=10
      - --get-throttling-time-ms=10
      - --log-level=error
    ports:
      - '8888:8888'
    volumes:
      - ../approot/ghcache:/cache/
    depends_on:
      redis:
          condition: service_started
