#!/bin/bash

#
# *******************************************************************************
# Copyright (c) 2024 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the MIT License
# which is available at https://spdx.org/licenses/MIT.html
# SPDX-License-Identifier: MIT
# *******************************************************************************
#

set -o errexit
set -o pipefail
set -o nounset

.venv/bin/hypercorn --config hypercorn-cfg.toml otterdog.app
