#  *******************************************************************************
#  Copyright (c) 2024-2025 Eclipse Foundation and others.
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License 2.0
#  which is available at http://www.eclipse.org/legal/epl-v20.html
#  SPDX-License-Identifier: EPL-2.0
#  *******************************************************************************

import re
from datetime import UTC, datetime
from logging import getLogger
from typing import Any, Self

from quart import current_app

from otterdog.utils import expect_type, unwrap
from otterdog.webapp.webhook.github_models import WorkflowRun

from . import Policy, PolicyType

logger = getLogger(__name__)


class ProjectPermissionsReviewPolicy(Policy):
    """
    A policy to create periodic GitHub issues for reviewing maintainer and collaborator permissions.
    """

    workflow_filter: str
    issue_title: str = "Periodic Review: Project Permissions"
    artifact_name: str | None = None

    @property
    def type(self) -> PolicyType:
        return PolicyType.PROJECT_PERMISSIONS_REVIEW

    def matches_workflow(self, workflow: str) -> bool:
        return re.search(self.workflow_filter, workflow) is not None

    def merge(self, other: Self) -> Self:
        copy = super().merge(other)
        copy.workflow_filter = other.workflow_filter
        copy.issue_title = other.issue_title
        if other.artifact_name is not None:
            copy.artifact_name = other.artifact_name
        return copy

    async def evaluate(
        self,
        installation_id: int,
        github_id: str,
        repo_name: str | None = None,
        payload: Any | None = None,
    ) -> None:
        repo_name = unwrap(repo_name)
        payload = expect_type(payload, WorkflowRun)

        if (
            payload.conclusion == "success"
            and payload.referenced_workflows is not None
            and any(self.matches_workflow(x.path) for x in payload.referenced_workflows)
        ):
            from otterdog.webapp.tasks.policies.project_permissions_review import (
                ProjectPermissionsReviewTask,
            )

            logger.info(
                f"workflow run {payload.name}/#{payload.id} in repo '{github_id}/{repo_name}' "
                f"triggers project permissions review"
            )

            current_app.add_background_task(
                ProjectPermissionsReviewTask(
                    installation_id,
                    github_id,
                    repo_name,
                    self,
                    payload.id,
                )
            )
        else:
            logger.debug(
                f"conditions not met to trigger project permissions review: \n"
                f"    workflow_filter={self.workflow_filter}, \n"
                f"    payload.conclusion={payload.conclusion}, \n"
                f"    payload.referenced_workflows={payload.referenced_workflows}, \n"
                f"    matches_workflow={any(self.matches_workflow(x.path) for x in payload.referenced_workflows or [])}"
            )

    def get_issue_body(self, repo_name: str, github_id: str, custom_body: str | None = None) -> str:
        """Generate the issue body for the project permissions review."""
        if custom_body:
            return custom_body

        current_year = datetime.now(UTC).year
        return f"""## {current_year} Project Permissions Review

This is a periodic review to ensure that access permissions for this repository and related services remain appropriate and secure.

- [ ] **Review Current Access**: Verify that all maintainers/commiters and collaborators still require their current level of access
- [ ] **Evaluate Activity**: Check recent contribution activity to ensure accounts are active
- [ ] **Security Audit**: Remove unused or unnecessary permissions
- [ ] **Update Documentation**: Ensure that any changes to permissions are documented appropriately
---

*This issue was automatically generated by Otterdog's project permissions review policy.*
"""
