query($endCursor: String, $organization: String!, $repository: String!) {
  repository(owner: $organization, name: $repository) {
    nameWithOwner
    branchProtectionRules(first: 100, after: $endCursor) {
      nodes {
        pattern
        allowsDeletions
        allowsForcePushes
        blocksCreations
        bypassForcePushAllowances(first: 100) {
          nodes {
            actor {
              ... on App {
                id
                slug
              }
              ... on Team {
                id
                slug
              }
              ... on User {
                id
                login
              }
            }
          }
        }
        bypassPullRequestAllowances(first: 100) {
          nodes {
            actor {
              ... on App {
                id
                slug
              }
              ... on Team {
                id
                slug
              }
              ... on User {
                id
                login
              }
            }
          }
        }
        dismissesStaleReviews
        isAdminEnforced
        pushAllowances(first: 100) {
          nodes {
            actor {
              ... on App {
                id
                slug
              }
              ... on Team {
                id
                slug
              }
              ... on User {
                id
                login
              }
            }
          }
        }
        requiredApprovingReviewCount
        requiredStatusCheckContexts
        requiredStatusChecks {
          app {
            slug
          }
        }
        requiresApprovingReviews
        requiresCodeOwnerReviews
        requiresCommitSignatures
        requiresConversationResolution
        requiresLinearHistory
        requiresStatusChecks
        requiresStrictStatusChecks
        restrictsPushes
        restrictsReviewDismissals
        reviewDismissalAllowances(first: 100) {
          nodes {
            actor {
              ... on App {
                id
                slug
              }
              ... on Team {
                id
                slug
              }
              ... on User {
                id
                login
              }
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}

