apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: otterdog  # Fixed: was foundation-internal-security-otterdog
  labels:
    app: mongodb
    environment: dev
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongodb
    environment: dev
